# Generated by Django 4.2 on 2023-12-10 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_discount_tax_order_discount_order_tax'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ('rate',), 'verbose_name': 'Скидка', 'verbose_name_plural': 'Скидки'},
        ),
        migrations.AlterModelOptions(
            name='tax',
            options={'ordering': ('rate',), 'verbose_name': 'Налог', 'verbose_name_plural': 'Налоги'},
        ),
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(default='RUB', max_length=5, verbose_name='Валюта'),
            preserve_default=False,
        ),
    ]
