# Generated by Django 4.2 on 2023-12-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_alter_discount_options_alter_tax_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('RUB', 'Russian Ruble')], max_length=5, verbose_name='Валюта'),
        ),
    ]
